### ISSUE TITLE
Datasets cannot be sorted by quality nor assay count

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#385]

**Comment by arteymix** [comment]
Looks like it's only the quality that is broken at the moment.

**Comment by arteymix** [comment]
I think it's fixed now, so only needs testing.

**Comment by arteymix** [comment]
Ok, just quality, I'll look into it now.

**Comment by ppavlidis** [comment]
Still applies in 2.0-alpha; needs focused follow-up. Audited during 2.0-alpha bug triage. arteymix reported the quality sort was partially fixed; verify in 2.0-alpha against the current dataset listing endpoint, and re-test assay-count ordering as well.

**Comment by ppavlidis** [comment]
Re-verified on `phase2-acl-migrate` (2.0-alpha).

The dataset listing endpoint (`GET /datasets`) sort path is end-to-end functional for both `bioAssayCount` (= `bioAssays.size`) and `geeq.publicQualityScore` / `geeq.publicSuitabilityScore`:

- **Assay count**: `ExpressionExperimentDaoImpl#resolveFilterablePropertyMeta` line 4402-4404 aliases `bioAssayCount` → `bioAssays.size` → `FilterQueryUtils#formOrderByClause` emits `order by size(ee.bioAssays)` (lines 34-36). Valid HB6 HQL.
- **Quality / suitability**: lines 4405-4412 resolve to a CASE expression with `objectAlias=null`:
  `(case when geeq.manualQualityOverride = true then geeq.manualQualityScore else geeq.detectedQualityScore end)`. `formProperty` returns the expression as-is; the surrounding HQL `left join ee.geeq as geeq` (lines 4179, 4202) brings the alias into scope.
- **Null ordering**: the 2023 GEEQ-specific `getSort` override in `DatasetArgService` that prepended a `(case when ... is not null then 0 else 1 end)` was removed in `d6dcdb2711` ("Add support for null ordering behavior") in favour of the general `Sort.NullMode` support — REST callers get `nulls last` as the default.

Coverage: `FilteringVoEnabledServiceIntegrationTest#testSortingByAllFilterableProperties` exercises every registered filterable property (including `bioAssayCount`, `bioAssays.size`, `geeq.publicQualityScore`, `geeq.publicSuitabilityScore`) through real HQL execution against MySQL. With the Criteria-API skip removed (commit `f69c42b797`, closes #520), all .size sort paths are now in the sweep.

Closing as verified-fixed by the cumulative Phase 2 / Phase 3 work. Re-open with a concrete failing call if quality or assay-count sort still misbehaves in the curation-UI.

**Comment by ppavlidis** [comment]
Gemma 2 disposition: Fixed
